### ISSUE TITLE
Warn users if very bad parameters are used

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu-notebooks#71]
Heard in a feedback call about OGGM-Edu today:

it would be good to have viable ranges for parameters (e.g. ELA, slope, Glen A, spatial resolution...) and warn the users when the set parameters exceed this range.

**Comment by Holmgren825** [comment]
I think this would be good as well. I can implement this along with fixes for other current issues. Do you have any viable ranges in mind?

**Comment by fmaussion** [comment]
Glen A: factor 1/10 10 
fs : same I guess
ELA: max and min h of bed
spatial resolution: not below 50m 
etc.

**Comment by fmaussion** [comment]
Actually A min should be from the table with -50°C
