### ISSUE TITLE
Transpose Glacier.summary df

### ISSUE THREAD

**Issue by Holmgren825** [OGGM/oggm-edu-notebooks#74]
The `Glacier.summary()`, and the html representation, is not able to display very small numbers. I encountered this when trying to add the creep and basal sliding to the parameters displayed. This has to to do with how pandas deals with data types. Since the df currently is a single column with many rows for the different params, the data type of the column is 'object'. To display numbers in a scientific format i.e 2.4e-27, a column has to have a numeric data type. We can fix this by simply transposing the `Glacier.summary` df, much like what the `GlacierCollection.summary` looks like. IMO the current summary df looks nicer for a single glacier, but it is not functional so we have to compromise.

**Comment by fmaussion** [comment]
Another solution would be to allays display A and fs as a factor of the default ones in the summary.
