### ISSUE TITLE
Issue on page /oggm-edu/glacier_water_resources_projections.html

### ISSUE THREAD

**Issue by Richteny** [OGGM/oggm-edu-notebooks#77]
In code blocks 28 and 29 the labelling of the RGI ID in the runoff timeseries is switched, i.e. the title for the Eastern Himalaya Glacier timeseries is the RGI ID of Hintereisferner and vice versa.
Responsible code snippets:

Block 28 aka Hintereisferner (gdirs[1] = Himalaya Glacier, gdirs[0] = Hintereisferner):
ax.set_ylabel('Annual runoff (Mt)'); ax.set_xlabel('Year'); plt.title(gdirs[1].rgi_id); plt.legend();
-> ax.set_ylabel('Annual runoff (Mt)'); ax.set_xlabel('Year'); plt.title(gdirs[0].rgi_id); plt.legend();

and in Block 29 aka Eastern Himalaya Glacier:
ax.set_ylabel('Annual runoff (Mt)'); ax.set_xlabel('Year'); plt.title(rgi_id); plt.legend();
-> ax.set_ylabel('Annual runoff (Mt)'); ax.set_xlabel('Year'); plt.title(gdirs[1].rgi_id); plt.legend();

**Comment by TobiasSchilcher** [comment]
I mentioned the same issue here #75 and tried to create a pull request here #78 (I hope this works as intended)

**Comment by Richteny** [comment]
That's true, issue was already resolved then!
