### ISSUE TITLE
Broken link in Ice Flow parameters notebook

### ISSUE THREAD

**Issue by AlbClaudio** [OGGM/oggm-edu-notebooks#92]
In the Sliding parameter section of Ice flow parameters the link of Hans Oerlemans's paper about sliding parameter is broken.  

The proposed correct link is:

https://www.cambridge.org/core/journals/annals-of-glaciology/article/flowline-model-for-nigardsbreen-norway-projection-of-future-glacier-length-based-on-dynamic-calibration-with-the-historic-record/238EA486EB8CCBC77A0C292047FC03CD#

**Comment by pat-schmitt** [comment]
Hi, thank you for the report. I have just updated the link.
